### ISSUE TITLE
如果需要使用单双日实现访问不同的域名，这样做可以吗

### ISSUE THREAD

**Issue by ghost** [xyTom/cf-page-func-proxy#1]
RT

代码如下：
```javascript
const day1 = 'app0.herokuapp.com'
const day2 = 'app1.herokuapp.com'

export default {
    async fetch(request, env) {
      let url = new URL(request.url)
      if (url.pathname.startsWith("/")) {
        let day = new Date().getDay()
        if (day === 0) {
          host = day1
        } else {
          host = day2
        }
        url.hostname=host
        let response = new Response(url, request)
        return response(new_request)
      }
      return env.ASSETS.fetch(request);
    }
  };
```

**Comment by xyTom** [comment]
应该是可以实现的，但这个代码貌似有点小问题吧 这个if (day === 0) { 判断不了单双日吧

网上搜索了一下别人写的代码，但没有测试过，你可以参考一下

const SingleDay = 'cloudreve1.herokuapp.com'
const DoubleDay = 'cloudreve2.herokuapp.com'
const timezone = 'Etc/GMT+2'; 

addEventListener(
   "fetch",event => { 

       let localized_date = new Date(new Date().toLocaleString('en-US', { timeZone: timezone }));
       if (localized_date.getDate()%2) {
           host = SingleDay
       } else {
           host = DoubleDay
       }

       let url=new URL(event.request.url);
       url.hostname=host;
       let request=new Request(url,event.request);
       event. respondWith(
           fetch(request)
       )
   }
)
